export const FETCH_MENUS = "menu/fetchMenus"
export const FETCH_MENU_DETAIL = "menu/fetchMenuDetail"
export const FETCH_CATEGORIES = "menu/fetchCategories"
export const FETCH_CATEGORY = "menu/fetchMenus"
export const LOGIN_USER = "menu/fetchMenus"
export const CREATE_MENU = "menu/create"